# 1. 베이스 이미지 설정
FROM openjdk:17-jdk-slim

# 2. 작업 디렉토리 설정
WORKDIR /app

COPY .env ./

# 3. JAR 파일 복사
COPY build/libs/*.jar app.jar

# 4. 애플리케이션 실행
CMD ["java", "-jar", "app.jar"]

# 5. 컨테이너가 수신할 포트 지정
EXPOSE 8080