spring:
  config:
    activate:
      on-profile : test

  datasource:
    url: jdbc:mysql://localhost:3306/tradingDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb://root:1234@localhost:27017/chat-room-mongo?authSource=admin

  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_MAIL_ID}
    password: ${NAVER_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group

management:
  health:
    mail:
      enabled: false

aws:
  s3:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password
    bucket-name: my-bucket
    region: ap-northeast-1